config/routes.rb
Rails.application.routes.draw do
  resources :clothes
  resources :outfits
  resources :users

  get "/gttr", to: "application#gttr"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  delete "/gttr", to: "users#destroy"
  # delete "/outfit/:id", to: "outfit#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clothe.rb
class Clothe < ApplicationRecord
  has_many :user_clothes
  has_many :clothe_outfits
  has_many :outfits, through: :clothe_outfits
  has_many :users, through: :user_clothes

  def self.find_category(category)
    self.all.select do |clothe|
      clothe.category == category
    end
  end

end

app/models/clothe_outfit.rb
class ClotheOutfit < ApplicationRecord
  belongs_to :clothe
  belongs_to :outfit
end

app/models/outfit.rb
class Outfit < ApplicationRecord
  has_many :clothe_outfits
  has_many :clothes, through: :clothe_outfits
  belongs_to :user
  validates :clothes, presence: true
  # validates :name, presence: true
  # validates :name, length: {maximum: 15}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :user_clothes
  has_many :clothes, through: :user_clothes
  has_many :outfits

  validates :username, presence: true
  validates :username, uniqueness: true
  # validates :password, presence: true
  validates_presence_of :password, :if => :special?

  def possible_outfits
    Outfit.all.select do |outfit|
      outfit.clothes.reduce(true) {|curr, clothe| curr && self.clothes.include?(clothe)}
    end
  end

  private

  def make_sepcial
    @special = true
  end

  def special?
    @special
  end
end

app/models/user_clothe.rb
class UserClothe < ApplicationRecord
  belongs_to :user
  belongs_to :clothe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?
  helper_method :current_user
  # protect_from_forgery with: :null_session

  def gttr
    render :gttr
  end

	def current_user
		if session[:current_user_id]
			@user = User.find(session[:current_user_id])
      return @user
		end
	end

	def logged_in?
	!!current_user
	end

end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController

  def index
    @user = current_user
    @clothes = Clothe.all
  end

  def show
    @user = current_user
    find_clothe
  end

  private
  def clothe_params
    params.require(:clothe).permit(:name, :category, :color)
  end

  def find_clothe
    @clothe = Clothe.find(params[:id])
  end

end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  skip_before_action :verify_authenticity_token


  def index
		if current_user
			@outfits = Outfit.all
		else
      redirect_to login_path
    end
	end

  def new
    @shirts = Clothe.find_category("Shirt")
    @pants = Clothe.find_category("Pants")
    @footwears = Clothe.find_category("Footwear")
    if current_user
      @user = current_user
      @outfit = Outfit.new
    else
      redirect_to login_path
    end
  end

  def show
    @user = current_user
    find_outfit
  end

  def create
    if current_user
      @outfit = Outfit.new(name: params[:outfit][:name])
      @outfit.user = current_user
      ids_arr = []
      ids_arr = params[:clothe_ids].values
      ids_arr.each {|id| @outfit.clothes << Clothe.find(id.to_i)}
      @outfit.save
      @outfit.clothes.each do |clothe|
        UserClothe.find_or_create_by(clothe_id: clothe.id, user_id: current_user.id)
      end
      if @outfit.valid?
        redirect_to current_user
      else
        render :new
      end
    else
      redirect_to login_path
    end
  end

  def update
    find_outfit
    @outfit.update(name: params[:outfit][:name])
    ids_arr = params[:outfit][:clothe_ids].each {|id| @outfit.clothes}
    while ids_arr.map{|id| !id.empty?} == true
      @outfit.clothes << Clothe.find(id)
    end
    redirect_to outfits_path
  end

  def edit
    find_outfit
  end

  def destroy
    find_outfit
    @outfit.destroy
    redirect_to current_user
  end

  private
  def outfit_params
    params.require(:outfit).permit(:name, :date)
  end

  def find_outfit
    @outfit = Outfit.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  #Logged in

  def new
    render :new
  end

  def create
    @user = User.find_by(username: params["username"])
    if @user && @user.authenticate(params["password"])
      session[:current_user_id] = @user.id
      redirect_to outfits_path
    else
      redirect_to "/login"
    end
  end

  def destroy
    session.delete :current_user_id
    redirect_to "/login"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    if @user.valid?
      redirect_to login_path
    else
      render :new
    end
  end

  def show
    find_user
  end

  def edit
    find_user
  end

  def update
    find_user
    # byebug
    @user.update(user_params)
    redirect_to @user
  end

  def destroy
    find_user
    @user.destroy
    @user.outfits.each do |outfit|
      outfit.destroy
    end
    redirect_to gttr_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :bio, :display_name)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clothe_outfits_helper.rb
module ClotheOutfitsHelper
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/gttr.html.erb
<%= image_tag "models/gttr-index-edited3.jpg", id:"index-img" %>
<h1>gttr</h1>

<button id="login-btn"><%= link_to "Login", login_path %></button>
<button id="signup-btn"><%= link_to "Sign Up", signup_path %></button>

<p>&copy; mi-gyna</p>

app/views/clothes/index.html.erb
<div class="sidenav">
  <div id="nav-container">
    <a href="#shirts">Shirt</a>
    <a href="#pants">Pant</a>
    <a href="#">Dress</a>
    <a href="#">Footwear</a>
    <a href="#">Accessories</a>
    <a href="#">Misc</a>
  </div>
</div>
<div class="main">
  <div class="main-nav">
    <button><a href="#">Log Out</a></button>
    <button><a href="#">Create</a></button>
    <button><a href="#">Explore</a></button>
  </div>
  <div id="shirts">
    <%= image_tag "shirts/army-green-shirt.jpg" %>
    <%= image_tag "shirts/blue-plaid.jpg" %>
    <%= image_tag "shirts/checkered-shirt.jpeg" %>
    <%= image_tag "shirts/fitted-blue-button-up.jpg" %>
    <%= image_tag "shirts/fitted-pink-button-up.jpg" %>
    <%= image_tag "shirts/fitted-white-button-up.jpg" %>
    <%= image_tag "shirts/gucci-rose-hoodie.jpeg" %>
    <%= image_tag "shirts/gucci-stranger-things-hoodie.png" %>
    <%= image_tag "shirts/long-baseball-tee.png" %>
    <%= image_tag "shirts/octocat-shirt.png" %>
    <%= image_tag "shirts/orange-hoodie.jpg" %>
    <%= image_tag "shirts/pug-life-shirt.jpg" %>
    <%= image_tag "shirts/pug-shirt.jpg" %>
    <%= image_tag "shirts/pugtato-shirt.jpg" %>
    <%= image_tag "shirts/the-office-aqua-blue-shirt.png" %>
  </div>
  <div id="pants">
    <%= image_tag "pants/black-shorts.jpg" %>
    <%= image_tag "pants/black-skirt-belt.jpeg" %>
    <%= image_tag "pants/black-skirt.jpg" %>
    <%= image_tag "pants/blue-green-plaid-skirt.jpeg" %>
    <%= image_tag "pants/brick-pants.jpg" %>
    <%= image_tag "pants/dripping-space-sweatpants.jpg" %>
    <%= image_tag "pants/grey-sweatshorts.png" %>
    <%= image_tag "pants/grey-straight-pant.jpg" %>
    <%= image_tag "pants/grey-sweatpants.jpg" %>
    <%= image_tag "pants/grey-sweatshorts.png" %>
    <%= image_tag "pants/hundred-sweatpants.jpg" %>
    <%= image_tag "pants/khaki-cuff-joggers.jpg" %>
    <%= image_tag "pants/light-blue-jeans.jpg" %>
    <%= image_tag "pants/light-pink-shorts.jpg" %>
    <%= image_tag "pants/long-red-skirt.jpg" %>
    <%= image_tag "pants/mens-leggings.jpg" %>
    <%= image_tag "pants/navy-blue-ruffle-skirt.jpeg" %>
    <%= image_tag "pants/navy-blue-skirt.jpeg" %>
    <%= image_tag "pants/neon-blue-shorts.jpg" %>
    <%= image_tag "pants/olive-green-pant.jpg" %>
    <%= image_tag "pants/olive-khaki-pants.jpg" %>
    <%= image_tag "pants/powered-by-plants-sweatpants.png" %>
    <%= image_tag "pants/red-spiral-long-skirt.jpg" %>
    <%= image_tag "pants/rooster-sweatpants.png" %>
    <%= image_tag "pants/sky-blue-sweatshorts.jpg" %>
    <%= image_tag "pants/tan-skirt.jpg" %>
    <%= image_tag "pants/wheat-pants.jpg" %>
    <%= image_tag "pants/womens-dark-jean-shorts.jpg" %>
    <%= image_tag "pants/womens-grey-leggings.jpg" %>
    <%= image_tag "pants/yellow-plaid-skirt.png" %>
  </div>
</div>

app/views/clothes/show.html.erb
<h2>Name: <%= @clothe.name %></h2>
<h5>Color: <%= @clothe.color %></h5>
<li>Category: <%= @clothe.category %></li>
<button><%= link_to "My Account", user_path(@user) %></button>
<button><%= link_to "Explore", outfits_path %></button>
<button><%= link_to "Log Out", logout_path, method: :delete %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gttr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless controller_name == "application" || controller_name == "sessions" || current_page?(signup_path) %>
      <nav>
        <h1>gttr</h1>
        <ul>
          <li><%= link_to "Log Out", logout_path, method: :delete %></li>
          <li><%= link_to "My Account", @user %></li>
          <li><%= link_to "Create", new_outfit_path %></li>
          <li><%= link_to "Explore", outfits_path %></li>
        </ul>
      </nav>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/outfits/edit.html.erb
<h1>Edit an Outfit</h1>
<%= form_for @outfit, html: { autocomplete: "off" } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.collection_check_boxes :clothe_ids, Clothe.all, :id, :name %>
  <%= f.submit "Submit" %>
<% end %>

<%= params.inspect %>

app/views/outfits/index.html.erb
<!-- css -->
  <div class="main-nav">
    <button><%= link_to "Log Out", logout_path, method: :delete %></button>
    <button><%= link_to "My Account", @user %></button>
    <button><%= link_to "Create", new_outfit_path %></button>
  </div>
  <div class="all-outfits">
    <% @outfits.each do |outfit| %>
      <% user_id = outfit.user_id %>
      <div class="all-outfit-margin index-all-outfits">
        <h4><%= link_to outfit.name, User.find(user_id) %></h4>
        <% outfit.clothes.each do |clothe| %>
          <div class="outfit-clothe">
            <%= image_tag clothe.url %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/outfits/new.html.erb
<!-- css -->

<div class="sidenav">
  <h1 id="top">gttr</h1>
  <div id="nav-container">
    <a href="#shirts">Shirt</a>
    <a href="#pants">Pant</a>
    <a href="#">Dress</a>
    <a href="#footwear">Footwear</a>
    <a href="#">Accessories</a>
    <a href="#">Misc</a>
  </div>
</div>

<div class="main">
  <div class="main-nav">
  </div>
  <ul class="modal-content">
    <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |error| %>
    <li class="error-message">*<%= error %></li>
    <% end %>
    <% end %>
  </ul>
  <div class="new-outfit-form">
    <%= form_for @outfit, html: { autocomplete: "off" } do |f| %>
      <div class="create-outfit-form">
        <%= f.label 'Name Your Outfit:' %>
        <%= f.text_field :name %>
        <%= f.submit "Create" %>
      </div>
      <div id="shirts" class="select-clothes">
        <% @shirts.each do |shirt| %>
          <%= image_tag shirt.url %>
          <%= radio_button_tag 'clothe_ids[shirt]', shirt.id %>
        <% end %>
      </div>
      <div id="pants" class="select-clothes">
        <% @pants.each do |pant| %>
          <%= image_tag pant.url %>
          <%= radio_button_tag 'clothe_ids[pant]', pant.id %>
        <% end %>
      </div>
      <div id="footwear" class="select-clothes">
        <% @footwears.each do |footwear| %>
          <%= image_tag footwear.url %>
          <%= radio_button_tag 'clothe_ids[footwear]', footwear.id %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<button onclick="topFunction()" class="top"><a href="#top">^</a></button>

<script type="text/javascript">
  function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
  }
</script>

app/views/outfits/show.html.erb
<%= @outfit.name %>
<% @outfit.clothes.each do |clothe| %>
  <%= clothe.name %>
<% end %>
<button><%= link_to "Delete Outfit", @outfit, method: :delete %></button><br>
<button><%= link_to "Edit Outfit", edit_outfit_path %></button>
<button><%= link_to "My Account", user_path(@user) %></button>
<button><%= link_to "Explore", outfits_path %></button>
<button><%= link_to "Log Out", logout_path, method: :delete %></button>

app/views/users/edit.html.erb
<!-- # <%= form_for @user, html: { autocomplete: "off" } do |f| %>
#   <%= f.label :display_name %>
#   <%= f.text_field :display_name %>
#   <%= f.label :bio %>
#   <%= f.text_area :bio %>
#   <%= f.submit %>
# <% end %> -->

<div class="sidenav profile">
  <h1>gttr</h1>
  <%= image_tag "models/willowsmith.jpg", class:"profile-img" %>
  <div class="user-edit">
    <%= form_for @user, html: { autocomplete: "off" } do |f| %>
      <%= f.label :display_name %>
      <%= f.text_field :display_name %>
      <%= f.label :bio %>
      <%= f.text_area :bio %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

<div class="main">
  <div class="main-nav">
    <button><%= link_to "Log Out", logout_path, method: :delete %></button>
    <button><%= link_to "Create", new_outfit_path %></button>
    <button><%= link_to "Explore", outfits_path %></button>
  </div>
  <div class="user-outfits">
    <% if @user.outfits.empty? %>
        <p style="margin:50px;">No outfits to show</p>
    <% else %>
        <% @user.outfits.each do |outfit| %>
        <div class="outfit">
          <h3><%= outfit.name %></h3>
          <span><%= link_to "x", outfit, method: :delete %></span>
          <% outfit.clothes.each do |clothe| %>
            <div class="outfit-clothe">
              <%= image_tag clothe.url %>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>All Users</h1>
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.display_name, user %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<%= image_tag "models/gttr-index-edited3.jpg", id:"index-img" %>
<h1>gttr</h1>
<button id="login-btn"><%= link_to "Login", login_path%></button>
<button id="signup-btn"><%= link_to "Sign Up", signup_path %></button>
<p>&copy; mi-gyna</p>

<div class="modal">
  <div class="modal-content">
    <div class="form-container">
        <ul class="modal-content">
          <% if @user.errors.any? %>
            <% @user.errors.full_messages.each do |error| %>
              <li class="error-message">*<%= error %></li>
            <% end %>
          <% end %>
        </ul>
      <div class="login-form" id="signup">
        <span class="close"><%= link_to "x", '/gttr' %></span>
          <%= form_for @user, html: { autocomplete: "off" } do |f| %>
            <%= f.label :username %>
            <%= f.text_field :username %>
            <%= f.label :display_name %>
            <%= f.text_field :display_name %>
            <%= f.label :password %>
            <%= f.password_field :password %>
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation  %>
            <%= f.submit %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<!-- <h1> <%= @user.display_name %> </h1>
<p> <%= @user.bio %> </p>
<% if @user.outfits.empty? %>
    <h1>No Outfits</h1><br>
    <button><%= link_to "Create an Outfit!", new_outfit_path %></button><br>
<% else %>
    <h1>My Outfits</h1>
    <% @user.outfits.each do |outfit| %>
    <h3><%= link_to outfit.name, outfit %></h3>
<% end %>
  <button><%= link_to "Create a New Outfit!", new_outfit_path %></button><br>
<% end %><br>
<button><%= link_to "Explore", outfits_path %></button>
<button><%= link_to "All Clothes", clothes_path %></button><br>
<button><%= link_to "Edit Profile", edit_user_path %></button>
<button><%= link_to "Delete Account", user_path, method: :delete %></button>
<button><%= link_to "Log Out", logout_path, method: :delete %></button> -->

<!-- css -->

<div class="sidenav profile">
  <h1>gttr</h1>
  <%= image_tag "models/willowsmith.jpg", class:"profile-img" %>
  <div class="user-info">
    <h3><%= @user.display_name %></h3>
    <p>(@<%= @user.username %>)</p><br>
    <p>____________________________________</p>
    <p><%= @user.bio %></p>
    <% if @user == current_user %>
      <button><%= link_to "Delete Account", user_path, method: :delete %></button>
      <button><%= link_to "Edit Profile", edit_user_path(@user) %></button>
    <% end %>
  </div>
</div>

<div class="main">
  <div class="main-nav">
    <button><%= link_to "Log Out", logout_path, method: :delete %></button>
    <button><%= link_to "Create", new_outfit_path %></button>
    <button><%= link_to "Explore", outfits_path %></button>
  </div>
  <div class="user-outfits">
    <% if @user.outfits.empty? %>
        <p style="margin:50px;">No outfits to show</p>
    <% else %>
        <% @user.outfits.each do |outfit| %>
        <div class="outfit">
          <h3><%= outfit.name %></h3>
          <span><%= link_to "x", outfit, method: :delete %></span>
          <% outfit.clothes.each do |clothe| %>
            <div class="outfit-clothe">
              <%= image_tag clothe.url %>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>